title: Álvaro Gómez Giménez
email: gomez.gimenez.alvaro@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Soy Ingeniero en Informática por la 
  Escuela Politécnica Superior (UAM), pianista, arreglista y compositor.
baseurl: "" # the subpath of your site, e.g. /blog
url: "gomezgimenez.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  alvarogimenez

markdown: kramdown
kramdown: 
  parse_block_html: true
  parse_inline_html: true

# Build settings
theme: minima
google_analytics: UA-171640276-1
show_excerpts: true
paginate: 5
paginate_path: /page/:num/
plugins:
  - jekyll-feed
  - jekyll-paginate